# Generated by Django 5.0.6 on 2024-07-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='file_assignment',
            field=models.FileField(blank=True, null=True, upload_to='assignment_created'),
        ),
    ]
